const DATA_URL='./data/candidatos.json';
const RESULTS_URL='./data/resultados.json';
const FAVORITES_KEY='eleicoes2026_favoritos';
let candidates=[]; let results=[];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function getFavs(){try{return JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]')}catch{return[]}}
function setFavs(v){localStorage.setItem(FAVORITES_KEY,JSON.stringify(v)); updateFavCount()}
function isFav(id){return getFavs().includes(String(id))}
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));if(page==='candidates')renderCandidates();if(page==='favorites')renderFavorites();if(page==='results')renderResults();history.replaceState(null,'','#'+page)}
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
function esc(x=''){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function normalize(c,i){return {...c,id:String(c.id??c.id_candidato??c.sq_candidato??i),nm_urna:c.nm_urna??c.nome_urna??c.nome??'',cargo:c.cargo??c.ds_cargo??'',sg_uf:c.sg_uf??c.uf??'',sg_partido:c.sg_partido??c.partido??'',nr_candidato:c.nr_candidato??c.numero??'',ds_situacao:c.ds_situacao??c.situacao??''}}
function card(c){const fav=isFav(c.id);return `<article class="card"><div class="top"><div class="avatar">${esc((c.nm_urna||'?').slice(0,1))}</div><button class="star" title="${fav?'Remover dos favoritos':'Favoritar'}" onclick="toggleFav('${esc(c.id)}')">${fav?'★':'☆'}</button></div><h3>${esc(c.nm_urna)}</h3><p>${esc(c.cargo||'')} · ${esc(c.sg_uf||'Brasil')}</p><p>${esc(c.sg_partido||'')} ${c.nr_candidato?'· nº '+esc(c.nr_candidato):''}</p>${c.ds_situacao?`<span class="tag">${esc(c.ds_situacao)}</span>`:''}</article>`}
function populateFilters(){const ufs=[...new Set(candidates.map(c=>c.sg_uf).filter(Boolean))].sort();const cargos=[...new Set(candidates.map(c=>c.cargo).filter(Boolean))].sort();$('#uf').innerHTML='<option value="">Todos os estados</option>'+ufs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('#cargo').innerHTML='<option value="">Todos os cargos</option>'+cargos.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function filtered(){const q=$('#q').value.trim().toLowerCase(),uf=$('#uf').value,cargo=$('#cargo').value;return candidates.filter(c=>(!q||[c.nm_urna,c.nr_candidato,c.sg_partido,c.cargo,c.sg_uf].join(' ').toLowerCase().includes(q))&&(!uf||c.sg_uf===uf)&&(!cargo||c.cargo===cargo))}
function renderCandidates(){const data=filtered();$('#candidateCount').textContent=data.length+' exibidos';$('#candidateGrid').innerHTML=data.length?data.map(card).join(''):`<div class="card"><h3>Nenhum candidato encontrado</h3><p>Tente mudar os filtros.</p></div>`}
function renderFavorites(){const favs=new Set(getFavs());const data=candidates.filter(c=>favs.has(String(c.id)));$('#favoriteGrid').innerHTML=data.length?data.map(card).join(''):`<div class="card"><h3>Você ainda não favoritou candidatos</h3><p>Abra a aba Candidatos e clique na estrela dos seus candidatos.</p></div>`}
function renderResults(){const favs=new Set(getFavs());const data=results.filter(r=>favs.has(String(r.id??r.id_candidato??r.sq_candidato??'')));if(!data.length){$('#resultsBox').innerHTML=`<div class="card"><h3>${favs.size?'Resultados ainda não disponíveis':'Nenhum favorito'}</h3><p>${favs.size?'Os arquivos de resultados ainda não foram conectados. Quando houver dados em <code>data/resultados.json</code>, somente seus favoritos aparecerão aqui.':'Favorite candidatos para acompanhá-los nesta aba.'}</p></div>`;return}$('#resultsBox').innerHTML=data.map(x=>`<article class="result-card"><div class="rline"><div><h3>${esc(x.nome??x.nm_urna??'')}</h3><small>${esc(x.cargo||'')} · ${esc(x.uf||x.sg_uf||'')}</small></div><div class="votes">${Number(x.votos||0).toLocaleString('pt-BR')}</div></div><div class="bar"><i style="width:${Math.min(100,Number(x.percentual||0))}%"></i></div><p>${Number(x.percentual||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}% · ${x.colocacao?x.colocacao+'º lugar':''}</p></article>`).join('')}
function toggleFav(id){const favs=new Set(getFavs());const key=String(id);favs.has(key)?favs.delete(key):favs.add(key);setFavs([...favs]);renderCandidates();renderFavorites();renderResults()}
function updateFavCount(){$('#favCount').textContent=getFavs().length}
async function loadJson(url,fallback){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error();return await r.json()}catch{return fallback}}
async function boot(){const raw=await loadJson(DATA_URL,[]);candidates=(Array.isArray(raw)?raw:(raw.candidates||raw.candidatos||[])).map(normalize);results=await loadJson(RESULTS_URL,[]);if(!Array.isArray(results))results=results.results||results.resultados||[];$('#total').textContent=candidates.length.toLocaleString('pt-BR');updateFavCount();populateFilters();['input','change'].forEach(ev=>{$('#q').addEventListener(ev,renderCandidates);$('#uf').addEventListener(ev,renderCandidates);$('#cargo').addEventListener(ev,renderCandidates)});const hash=location.hash.slice(1);if(['candidates','favorites','results'].includes(hash))go(hash);else renderCandidates()}
boot();
